/*
 * Generated by MTK SP Drv_CodeGen Version 03.13.6 for MT6572_NP. Copyright MediaTek Inc. (C) 2013.
 * Sun Feb 21 00:53:10 2016
 * Do Not Modify the File.
 */

#ifndef __CUST_AUXADC_TOOL_H
#define __CUST_AUXADC_TOOL_H




#endif //_CUST_AUXADC_TOOL_H


